# Generated by Django 3.2.6 on 2022-08-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explane', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explane',
            options={'verbose_name': 'Объяснительная', 'verbose_name_plural': 'Объяснительные'},
        ),
    ]
