# Generated by Django 3.2.6 on 2022-08-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explane', '0002_alter_explane_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='explane',
            name='dt_orig',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время внесения записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explane',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explane',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='отсутствовал с'),
        ),
        migrations.AddField(
            model_name='explane',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='отсутствовал до'),
        ),
        migrations.AlterField(
            model_name='explane',
            name='date',
            field=models.DateField(verbose_name='Дата отсутствия'),
        ),
        migrations.AlterField(
            model_name='explane',
            name='explane',
            field=models.TextField(max_length=1000, verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='explane',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, внесший запись'),
        ),
    ]
